"""initial mvp schema

Revision ID: 69ebc353c5b4
Revises: 
Create Date: 2026-04-18 19:42:20.375280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69ebc353c5b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logistics_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(), nullable=True),
    sa.Column('base_fee_myr', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistics_routes_id'), 'logistics_routes', ['id'], unique=False)
    op.create_table('router_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_router_decisions_id'), 'router_decisions', ['id'], unique=False)
    op.create_table('skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skus_id'), 'skus', ['id'], unique=False)
    op.create_index(op.f('ix_skus_sku_id'), 'skus', ['sku_id'], unique=True)
    op.create_table('tax_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hs_code', sa.String(), nullable=True),
    sa.Column('bm_rate', sa.Float(), nullable=True),
    sa.Column('ppn_rate', sa.Float(), nullable=True),
    sa.Column('pph_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_rules_hs_code'), 'tax_rules', ['hs_code'], unique=False)
    op.create_index(op.f('ix_tax_rules_id'), 'tax_rules', ['id'], unique=False)
    op.create_table('compliance_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.sku_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_checks_id'), 'compliance_checks', ['id'], unique=False)
    op.create_table('profit_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.String(), nullable=True),
    sa.Column('margin_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.sku_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profit_calculations_id'), 'profit_calculations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profit_calculations_id'), table_name='profit_calculations')
    op.drop_table('profit_calculations')
    op.drop_index(op.f('ix_compliance_checks_id'), table_name='compliance_checks')
    op.drop_table('compliance_checks')
    op.drop_index(op.f('ix_tax_rules_id'), table_name='tax_rules')
    op.drop_index(op.f('ix_tax_rules_hs_code'), table_name='tax_rules')
    op.drop_table('tax_rules')
    op.drop_index(op.f('ix_skus_sku_id'), table_name='skus')
    op.drop_index(op.f('ix_skus_id'), table_name='skus')
    op.drop_table('skus')
    op.drop_index(op.f('ix_router_decisions_id'), table_name='router_decisions')
    op.drop_table('router_decisions')
    op.drop_index(op.f('ix_logistics_routes_id'), table_name='logistics_routes')
    op.drop_table('logistics_routes')
    # ### end Alembic commands ###
